### ISSUE TITLE
No Scroll in android

### ISSUE THREAD

**Issue by shaikhussian** [remobile/react-native-marquee-label#9]
hi, i tried marquee label in react-native android, text doesn't displays and scroll. please give me a suggestion to solve the issue.

**Comment by shaikhussian** [comment]
Please respond

**Comment by rknell** [comment]
For me the text didn't display until I set a height in the styles prop

**Comment by lavarajallu** [comment]
Mr@Hussain i  have a Solution  for this , when we are using text that text should contain height and width must.

like this......

```
<MarqueeLabel 
                        style={styles.marqueeLabel}
                        scrollDuration={20.0}>
                        Pro Football Scores: Pro Basketball 
            Pro Football Scores: Pro Basketball 
                    </MarqueeLabel>         
this is used for styles:
```
marqueeLabel: {

        backgroundColor: 'white'
        width:windowSize.width, 
        marginRight:50,
        height:20,
        fontSize:(Platform.OS === 'ios')?15:24,
        fontFamily:'Roboto-Regular',
        color:(Platform.OS === 'ios') ?'#092a53':'#092a53'
    },
```
```
